---
Description: Create one ec2 instance aws linux 2 with docker and static ip
Resources:
  instanciadocker:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
      - Key: Name
        Value: docker01
      AvailabilityZone: us-east-1a
      NetworkInterfaces:
      - Description: Primary Network Interface
        DeviceIndex: '0'
        SubnetId: subnet-915097f7
        PrivateIpAddress: 172.31.0.11
        GroupSet:
        - sg-03a75a7d741b59e23
      ImageId: ami-02354e95b39ca8dec
      InstanceType: t2.micro
      KeyName: key-pair-teste
      UserData:
        Fn::Base64:
          Fn::Join:
          - ''
          - - "#!/bin/bash -xe\n"
            - "yum update -y \n"
            - "amazon-linux-extras install -y docker \n"
            - "service docker start \n"
            - "systemctl enable docker \n"
            - "usermod -a -G docker ec2-user \n"
            - 'curl -L '
            - '"https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname
              -s)-$(uname -m)"'
            - " -o /usr/local/bin/docker-compose \n"
            - "chmod +x /usr/local/bin/docker-compose \n"
